# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7040ac1e26f2e53ec4b7f1768a805a8c6078f494fd1c4deb99f865d1aab6a1c778d62f16f95a64908a4520ff7d7c78e7ca8ecccaead063931d834a4458d2de5

test:
  secret_key_base: 540fdd7f4086892641c635a885545ab27bb8b598f4febd196df1417f9400e0474ece045d706d81a2e62e126e0e99ddefd60424d71df1febeddc7309219361f7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
